### ISSUE TITLE
USB relay keeps changing name when used with solenoid valve 

### ISSUE THREAD

**Issue by nhirsh** [umd-lhcb/rpi.burnin#9]
There is an issue of compatibility between the solenoid and the power supply and relay. Depending on it's last state, it is open  or closed without relation to what the relay says. However, when the relay switches states, so will the valve.

**Comment by yipengsun** [comment]
The original problems was that the USB relay would change name on subsequent operations.

**Comment by LegyPlegy** [comment]
https://github.com/pavel-a/usb-relay-hid/releases

testing purposes

**Comment by LegyPlegy** [comment]
The usb relay will change names only if the solenoid is connected. Tests on an empty channel work as expected, the relay turns off and on without issue.

I have also ruled out that the solenoid valve is faulty, since it ticks when connected directly to the power supply instead of through the relay.

I will resume testing tomorrow, my first guess is that the relay is resetting itself when it encounters an issue.

**Comment by LegyPlegy** [comment]
Very relevant information for coding the on/off switch: [Watchdog Timers](https://ncd.io/choosing-the-right-usb-relay-controller/#document-4)
Video for the solenoid valve operation. [Interesting](https://youtu.be/5rokXHhxRSw)
More valve reading material. [Link](https://www.rainbird.com/sites/default/files/media/documents/2017-06/man_ValveTroubleshootingMaintenance.pdf
)

**Comment by SummerLeaves** [comment]
Article with specifics on how to deal with high-inductive loads, specifically addresses the USB relay issue. 
https://ncd.io/controlling-inductive-devices-managing-electromagnetic-interference/

**Comment by LegyPlegy** [comment]
Quoted from Raymond's article: "Choosing the correct induction suppression capacitor is simply a matter of choosing the maximum voltage requirement of the device you are trying to control."

The Valve utilizes 24 Volts AC 50/60 Hz, however we are powering it with a 12V DC 4.2A power supply. The troubleshooting guide for the valve says it requires a minimum of 0.30 amps for opening the valve, and 0.19 amps to hold it open. (Page 7)

**Comment by LegyPlegy** [comment]
An alternative solution to the capacitor would be similar to what we discussed on Friday. Using information from [this article](https://progeny.co.uk/back-emf-suppression/) we can introduce a MOV (Metal Oxide Variable-Resistor) in conjunction with a diode in order to offload the voltage spikes from the USB relay.

**Comment by yipengsun** [comment]
I think we should try Tom's method first, also @SummerLeaves your method seems to for handling high-voltage inductor, but here we have a low-voltage one (12 V).

**Comment by LegyPlegy** [comment]
## USB Relay renaming issue has been solved. 

### Cause & Description of issue
The valve is operated by a solenoid connected in series with the relay and power supply. When flipping the switch, the rapid change in current induces a back-current (by Lenz's Law, opposite of the current going into the solenoid) which enters the relay through the common pin, which is an unintended side-effect of powering inductive loads with a relay
### Solution
In order to suppress the back-current induced by the coil, a diode was connected in parallel across the valve. Its anode was connected to the positive output of the power supply (which should be connected to the 1st valve wire), and its cathode was connected to the 2nd valve wire.
![img_0589](https://user-images.githubusercontent.com/40072973/51701472-828da600-1fdf-11e9-959d-78b3e2f43297.jpg)

The diode we used was the 50wq06fn, rated at a 60V maximum reverse voltage and 5.5 amp current.

## Next Steps
Testing flow using an air pump.

**Comment by LegyPlegy** [comment]
## Valves have been tested and there is good news!

###Valves labeled B, C, and D passed visual inspection
Valves were hooked up in series with an ammeter and the relay on the NO port. These valves draw about 0.243-0.259 amps of current each. Air flow is completely blocked while the USB Relay is OFF (LED on board is off). Air flow is unobstructed while the USB Relay is ON (LED on board is on). Future implementation of this code in the monitoring should utilize [watchdog timers](https://ncd.io/choosing-the-right-usb-relay-controller/#document-4). 

###Valve A is not functional.
Tests with this valve show that in all possible configurations the valve allows only a portion of the airflow to pass through. The solenoid can be heard clicking but the valve does not change its behavior when switched from ON/OFF. This valve has been labeled "BROKEN" and is the only valve not currently in a box in the undergraduate office.

I have also sketched a quick circuit diagram of the setup I used to test using [circuitlab](circuitlab.com) (free for UMD students), which is only missing an ammeter between the solenoid/diode and the NO terminal of the relay.
